### ISSUE TITLE
In VisionOS 2.0 Beta 1, Audio reliably cuts out within minutes

### ISSUE THREAD

**Issue by minusreality** [alvr-org/alvr-visionos#112] opened 2024-06-14 17:00 UTC
Within 2-3 minutes of starting a game, the audio stops operating. It continues to work if I close and re-open ALVR with no other changes. This issue was not present before VisionOS 2.0 Beta 1.

This issue is occuring for me in both the latest nightly build, and in testflight 20.7.1

**Comment by shinyquagsire23** [comment] 2024-06-14 19:12
Found a resolution to this, there's something extra weird going on with Mac Virtual Display because the sequence of events is

- Failure to get a DeviceAnchor (should NEVER happen)
- My app exit heuristic gets triggered, which turns off the audio to prevent crackling (crackling was fixed in visionOS 2, yay)
- A huge network spike is reported, greater than 600ms (should NEVER happen, but frankly the bar is in the floor for network reliability atm)

Fix will be deployed in the next stable/nightly releases, but be aware of the network spiking issue, that one is not my fault lol

**Comment by ant2002k** [comment] 2024-06-14 19:24
FWIW I’m running OS2.0 beta and most your most recent build and I had no sound issues.

**Comment by shinyquagsire23** [comment] 2024-06-14 19:25
that may have been coincidence, the bug *only* triggers with Mac Virtual Display active

**Comment by minusreality** [comment] 2024-06-14 20:27
I can confirm that I'm using this with Mac Virtual Display active.

**Comment by shinyquagsire23** [comment] 2024-08-01 19:56
oh right, I did fix this bug but the root cause (huge stutters with MVD) is still being fixed by Apple

**Closed** 2024-08-01 19:56 UTC
Labels: bug, resolved, Apple pls
